---
- name: Update dnsmasq config
  become: yes
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: dnsmasq restart

- name: Update dnsmasq dhcp reservation
  become: yes
  template:
    src: dhcp-hosts.conf.j2
    dest: /etc/dnsmasq.d/dhcp-hosts.conf
    owner: root
    group: root
    mode: 0644  
  notify: dnsmasq restart

- name: Update dnsmasq dns hosts
  become: yes
  template:
    src: dns-hosts.conf.j2
    dest: /etc/dnsmasq.d/dns-hosts.conf
    owner: root
    group: root
    mode: 0644  
  notify: dnsmasq restart

