---
# tasks file for dnsmasq

- name: install dnsmasq
  become: yes
  apt:
    name: dnsmasq
    state: latest

- name: disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
  become: yes

- name: configure dnsmasq
  include_tasks: 'config.yml'

- name: configure ufw
  include_tasks: 'ufw.yml'

