---
# handlers file for dnsmasq

- name: dnsmasq reload
  become: yes
  service: 
    name: dnsmasq
    state: reloaded

- name: dnsmasq restart
  become: yes
  service: 
    name: dnsmasq
    state: restarted
